# Generated by Django 3.2.9 on 2021-11-13 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Data de exclusão')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Categoria de Produto',
                'verbose_name_plural': 'Categorias de Produto',
            },
        ),
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Data de exclusão')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Unidade de Medida',
                'verbose_name_plural': 'Unidades de Medida',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Data de exclusão')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição do Produto')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagem do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Data de exclusão')),
                ('discount_value', models.PositiveSmallIntegerField(default=0)),
                ('category_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='indicador de oferta')),
            ],
            options={
                'verbose_name': 'Indicador de Oferta',
                'verbose_name_plural': 'Indicadores de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Data de criação')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Data de exclusão')),
                ('name', models.CharField(db_index=True, max_length=150, verbose_name='Nome do Produto')),
                ('description', models.TextField(verbose_name='Descrição do Produto')),
                ('image', models.TextField(blank=True, max_length=100, null=True, verbose_name='Imagem do Produto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Produto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMeasureUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Data de criação')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Data de exclusão')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Unidade de Medida',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicator',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Data de criação')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Data de exclusão')),
                ('discount_value', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('category_product', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='indicador de oferta')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Indicador de Oferta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalCategoryProduct',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Data de criação')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Data de modificação')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Data de exclusão')),
                ('description', models.CharField(db_index=True, max_length=50, verbose_name='Descrição')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('measure_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='unidade de medida')),
            ],
            options={
                'verbose_name': 'historical Categoria de Produto',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='measure_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='unidade de medida'),
        ),
    ]
